### ISSUE TITLE
Parameter Editor pop-up text format problems

### ISSUE THREAD

**Issue by junwoo091400** [mavlink/qgroundcontrol#10382]
## Expected Behavior
1. Texts shouldn't overlap with each other and be displayed in a correct way
2. It should use a reasonable width of QGC to display the description
3. Description should respect the Line spacing inside the PX4 Source code

## Current Behavior
- 'Default' value text is overlapping with the description above
![image](https://user-images.githubusercontent.com/23277211/187208449-7b7fb384-dc7d-4085-bed9-49b4934c7b3a.png)

- The width of Editor screen is limited, and the display is hard to view
![image](https://user-images.githubusercontent.com/23277211/187208827-6a51f9f8-6e08-4b42-837d-51d23d4a2dd8.png)

- The line endings (`\n`) get ignored. Due to the fact that parameters.json file that gets generated removes all the line endings. This needs to be fixed in PX4's side.
![image](https://user-images.githubusercontent.com/23277211/187213200-646edd05-5fbf-4414-bd9c-bffe3a01bbca.png)

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Flash PX4 `main`
2. Check EKF2_HGT_REF parameter's descriptions (overlapping)
3. Check EKF2_GPS_CHECK (text is squashed in a limited width frame)
4. Check EKF2_RNG_CTRL (text doesn't have line spacings in between)

## TODO
- [ ] Remove overlapping between description and 'default' value display
- [ ] Remove editor's width limit and allow it to use bigger width for better text viewing experience
- [ ] Allow user to copy the description (allow selecting tests via mouse)
- [ ] Don't remove line endings when creating parameters.json file in PX4 side

**Comment by booo** [comment]
Did this get fixed? Skimming through the referenced issue I can't really tell.

**Comment by junwoo091400** [comment]
> Did this get fixed? Skimming through the referenced issue I can't really tell.

Nope, not yet 😢, do you have a clue on how to fix it? I noticed this today again and reminded me how annoying this is haha

**Comment by HTRamsey** [comment]
Seems to be good now, please reopen if not.
